make: lint, mypy disable error code call-arg
getting dozens of mypy errors with upgraded pydantic (1.10.6) and mypy
(1.1.1); ...

```
tests/test_transform.py:57: error: Missing named argument "doaj_id" for
"ScholarBiblio"  [call-arg] tests/test_transform.py:57: error: Missing
named argument "dblp_id" for "ScholarBiblio"  [call-arg]
tests/test_transform.py:57: error: Missing named argument "oai_id" for
"ScholarBiblio"  [call-arg]
```

related: https://github.com/pydantic/pydantic/pull/5077

For the moment, try to follow dependency upgrades to not let the gap
become too larget; albeit these issues are time-consuming to sort out.